name: untitled
description: Flutter Base App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  domain:
    path: ./domain

  data:
    path: ./data

  core:
    path: ./core

  cupertino_icons: ^1.0.2
  talker: ^3.1.7
  auto_route: ^7.8.4
  intl: ^0.18.1
  mask_text_input_formatter: ^2.8.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  talker_bloc_logger: ^2.4.0
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  simple_animations: ^5.0.2
  talker_flutter: ^3.6.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2


flutter:
  generate:
    true
  assets:
    - .env

  uses-material-design: true
